```{r}
#COMPARISON OF ORIGINAL PAPER MODEL (WITH SMOOTHING) WITH NO SMOOTHING VERSION OF CONFORMAL REGRESSION
library(quantreg)
library(lubridate)
library(pracma)
library(readxl)
library(sn)
library(parallel)

h <- 4

# Load data 
file_path <- "DataVulnerabilityAppendix.xls"

# Read the file
data <- read_excel(file_path)
data<-data[,1:3]

# Filter data for 1973Q1-2015Q4
colnames(data)[1] <- "Time"
data$Time <- as.Date(data$Time)


# Subset the data
data <- data[data$Time >= as.Date("1973-01-01") & data$Time <= as.Date("2015-10-01"), ]
X <- data[,2:3]
Time <- data$Time


# Set forecast settings
QQ <- seq(0.05, 0.95, by = 0.05)
QQC <-  seq(0.01, 0.99, by = 0.01)
#QQ <- seq(0.01, 0.99, by = 0.01) #Let's try a much more fine grid 
#QQ <- c(0.01, QQ, 0.99)
deltaYY <- 0.1
YY <- seq(-20, 20, by = deltaYY)
jtFirstOOS <- which(year(data$Time) == 1993 & month(data$Time) == 1)
indices <- which(QQ %in% c(0.05, 0.25, 0.5, 0.75, 0.95))
jq05 <- indices[1]
jq25 <- indices[2]
jq50 <- indices[3]
jq75 <- 16 #couldn't automatically translate from MATLAB, I set it manually, no idea why
jq95 <- indices[4]

# Construct average growth rates
y <- X$A191RL1Q225SBEA
Yh <- matrix(0, nrow=length(y), ncol=4)


Yh <- stats::filter(y, rep(1/h, h), sides=1) #If h = 1, y = Yh
if (h>1){
  Yh[1:(h-1)] <- NA
}
```


```{r}
#  LOAD DATA FOR THE CONFORMAL CASE

filename <- paste("ResOOSC_H", h, ".RData", sep="")
cat(paste("Loading results from file", filename, "\n"))

load(filename)
```



```{r}
#  LOAD DATA FOR THE CASE WITH SMOOTHING (ORIGINAL)

filename <- paste("ResOOS_H", h, ".RData", sep="")
cat(paste("Loading results from file", filename, "\n"))

load(filename)

```



```{r}
#  COMPARE IN SAMPLE AND UNCONDITIONAL. THIS IS A EASY WAY TO TEST THE GOODNESS OF MY IMPLEMENTATION OF qst, dst, and pst

qqTargNS <- YQunc_ISC[nrow(YQunc_ISC), ]
qqTarg <- YQunc_IS[nrow(YQunc_IS), ]

densitiespNS <- PSTunc_ISC[h+1, ]         #dst function
densitiesp <- PSTunc_IS[h+1, ]
plot(YY,densitiespNS, xlab = 'grid', ylab='density')
points(YY,densitiesp, col = 'red')

densitiesqNS <- QSTunc_ISC[h+1, ]         #qst function
densitiesq <- QSTunc_IS[h+1, ]
plot(QQC,densitiesqNS, xlab = 'grid', ylab='empirical quantiles',)
points(QQ,densitiesq, col = 'red')

densitiescNS <- CSTunc_ISC[h+1, ]          #pst function
densitiesc <- CSTunc_IS[h+1, ]
plot(YY,densitiescNS, xlab = 'grid', ylab='empirical cumulative',)
points(YY,densitiesc, col = 'red')


plot(Yh[(h + 1):length(Yh)],ScoreSTunc_ISC[(h + 1):length(Yh)], xlab = 'real observations', ylab = 'density')   # dst function
points(Yh[(h + 1):length(Yh)],ScoreSTunc_IS[(h + 1):length(Yh)], col = 'red')



```
```{r}
#  NOW I COMPARE OUT-OF-SAMPLE FOR A RANDOM YEAR


jt <- 100 #higher than 81 if I want to test the OOS, OTHERWISE IS FULL ON NA

qqTargNS <- YQ_OOSC[jt + h, ]
qqTarg <- YQ_OOS[jt + h, ]

densitiespNS <- PST_OOSC[jt+h, ]         #dst function
densitiesp <- PST_OOS[jt+h, ]
plot(YY,densitiespNS, xlab = 'grid', ylab='density')
points(YY, densitiesp, col = 'red')

densitiesqNS <- QST_OOSC[jt+h, ]         #qst function
densitiesq <- QST_OOS[jt+h, ]
plot(QQC,densitiesqNS, xlab = 'grid', ylab='empirical quantiles',)
points(QQ,densitiesq, col = 'red')

densitiescNS <- CST_OOSC[jt+h, ]          #pst function
densitiesc <- CST_OOS[jt+h, ]
plot(YY,densitiescNS, xlab = 'grid', ylab='empirical cumulative',)
points(YY,densitiesc, col = 'red')

```

```{r}
# PLOT DOWNSIDE ENTROPY

plot(Time, LeftEntropy_OOSC, type = 'l', col = '#0000FF', 
     xlab = 'Time', ylab = 'Entropy', xlim = range(Time), ylim = c(-0.2,1.1),
     main = "Comparison of Entropies Over Time", lwd = 2)
lines(Time, LeftEntropy_OOS, type = 'l', col = '#008000',  lwd = 2) 
legend("topleft", 
       legend = c("LeftEntropy_OOSC", "LeftEntropy_OOS"), 
       col = c('#0000FF', '#008000'),
       lty = c(1, 1),  
       lwd = c(2, 2))  
       



plot(Time, LeftEntropy_ISC, type = 'l', col = '#0000FF',
     xlab = 'Time', ylab = 'Entropy', xlim = range(Time), ylim = c(-0.2,1.3),
     main = "Comparison of Entropies Over Time", lwd = 2)
lines(Time, LeftEntropy_IS, type = 'l', col = '#008000', lwd = 2) 
legend("topleft", 
       legend = c("LeftEntropy_ISC", "LeftEntropy_IS"), 
       col = c('#0000FF', '#008000'),
       lty = c(1, 1),  
       lwd = c(2, 2))  
```
```{r}
# PLOT OUT OF SAMPLE ACCURACY


plot(Time, ScoreST_OOSC, type = 'l', col = '#0000FF', 
     xlab = 'Time', ylab = 'Accuracy', xlim = range(Time), 
     main = "Comparison of Accuracies Over Time", lwd = 2)
lines(Time, ScoreST_OOS, type = 'l', col = '#008000',  lwd = 2) 
legend("topleft", 
       legend = c("ScoreST_OOSC", "ScoreST_OOS"), 
       col = c('#0000FF', '#008000'),
       lty = c(1, 1),  
       lwd = c(2, 2))  
       



plot(Time, ScoreST_ISC, type = 'l', col = '#0000FF', 
     xlab = 'Time', ylab = 'Accuracies', xlim = range(Time),
     main = "Comparison of Accuracies Over Time", lwd = 2)
lines(Time, ScoreST_IS, type = 'l', col = '#008000',  lwd = 2) 
legend("topleft", 
       legend = c("ScoreST_ISC", "ScoreST_IS"), 
       col = c('#0000FF', '#008000'),
       lty = c(1, 1),  
       lwd = c(2, 2))  
```
```{r}
PITtest_env <- new.env()
source("PITtest.r",local = PITtest_env)

rstestboot_env <- new.env()
source("rstestboot.r",local = rstestboot_env)

rvec <- seq(0, 1, by = 0.001)

if (h == 1) {
  kappa <- 1.34
  kappaGDPonly <- 1.34
  P <- sum(!is.na(PitST_OOSC)) # correct for both h = 1 and h = 4
} else if (h == 4) {
  # Compute bootstrapped 5% critical values
  PITs <- cbind(PitST_OOSC, PitSTGDPonly_OOSC)
  PITs <- PITs[(jtFirstOOS + h):nrow(PITs), , drop = FALSE]
  
  #testcritvalues <- matrix(NA, nrow = 1, ncol = 2, dimnames = list(NULL, c('GDP and NFCI', 'GDP only')))
  testcritvalues <- array(NA, dim = c(2, 3, 2))
  
  for (i in 1:2) {
    testcritvalues[,, i] <- round(rstestboot_env$rstestboot(PITs[, i])$critvalues[2] * 100) / 100
  }
  
  kappa <- testcritvalues[1, 2, 1] #different from Matlab due to seed in CVfinalbootstrapInoue
  kappaGDPonly <- testcritvalues[1, 2, 2] #different from Matlab due to seed in CVfinalbootstrapInoue
}
  # Create the data frame for the dashed lines
  dashed_lines <- data.frame(
    tau = rvec,
    lower = rvec - (kappa / sqrt(P)),
    upper = rvec + (kappa / sqrt(P))
  )



zST_ecdfNS <- PITtest_env$PITtest(PitST_OOSC, rvec)
zSTGDPonly_ecdfNS <- PITtest_env$PITtest(PitSTGDPonly_OOSC, rvec)

zST_ecdf <- PITtest_env$PITtest(PitST_OOS, rvec)
zSTGDPonly_ecdf <- PITtest_env$PITtest(PitSTGDPonly_OOS, rvec)

data3 <- data.frame(
  tau = rvec,
  PITC = zST_ecdfNS,
  PIT = zST_ecdf
)

data4 <- data.frame(
  tau = rvec,
  PITGDPonlyC = zSTGDPonly_ecdf,
  PITGDPonly = zSTGDPonly_ecdfNS
)

# Create the Line data separately
line_data <- data.frame(tau = rvec, Line = rvec)

# Reshape data for ggplot
data3_long <- data3 %>%
  pivot_longer(cols = -tau, names_to = "Series", values_to = "Value")

data4_long <- data4 %>%
  pivot_longer(cols = -tau, names_to = "Series", values_to = "Value")

# Define a common theme
custom_theme <- theme_minimal() +
  theme(
    axis.title = element_text(face = "bold", size = 14),
    axis.text = element_text(size = 12),
    legend.position = "top",
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_line(color = "grey90")
  )

# First new plot
plot3 <- ggplot(data3_long, aes(x = tau, y = Value, color = Series, linetype = Series)) +
  geom_line(size = 1) +
  geom_line(data = line_data, aes(x = tau, y = Line), color = "black", linetype = "dashed", size = 1.2, show.legend = FALSE) +
  geom_line(data = dashed_lines, aes(x = tau, y = lower), color = "black", linetype = "dashed", size = 1, show.legend = FALSE) +
  geom_line(data = dashed_lines, aes(x = tau, y = upper), color = "black", linetype = "dashed", size = 1, show.legend = FALSE) +
  scale_color_manual(values = c("PITC" = "blue", "PIT" = "red")) +
  scale_linetype_manual(values = c("PITC" = "solid", "PIT" = "solid")) +
  labs(x = expression(tau), y = 'Empirical CDF') +
  custom_theme +
  guides(color = guide_legend(title = NULL), linetype = guide_legend(title = NULL))

plot3
# Save the first new plot
ggsave("plotfullh1.png", plot = plot3, width = 8, height = 6, dpi = 300)

# Second new plot
plot4 <- ggplot(data4_long, aes(x = tau, y = Value, color = Series, linetype = Series)) +
  geom_line(size = 1) +
  geom_line(data = line_data, aes(x = tau, y = Line), color = "black", linetype = "dashed", size = 1.2, show.legend = FALSE) +
  geom_line(data = dashed_lines, aes(x = tau, y = lower), color = "black", linetype = "dashed", size = 1, show.legend = FALSE) +
  geom_line(data = dashed_lines, aes(x = tau, y = upper), color = "black", linetype = "dashed", size = 1, show.legend = FALSE) +
  scale_color_manual(values = c("PITGDPonlyC" = "blue", "PITGDPonly" = "red")) +
  scale_linetype_manual(values = c("PITGDPonlyC" = "solid", "PITGDPonly" = "solid")) +
  labs(x = expression(tau), y = 'Empirical CDF') +
  custom_theme +
  guides(color = guide_legend(title = NULL), linetype = guide_legend(title = NULL))

plot4
# Save the second new plot
ggsave("plotgdponlyh1.png", plot = plot4, width = 8, height = 6, dpi = 300)
```
